name: send qq email daily

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  
jobs: 
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 确保代码被检出到工作流中
        
      - name: send email
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py